name: Module test workflow
on: [push]
jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ES - Index Data
        uses: dagger/dagger-for-github@v5
        with:
          verb: call 
          module: github.com/mgreau/daggerverse/elasticsearch
          args: index-data --index="movies" --data ./datasets/movies.json

      - name: ES - Search
        uses: dagger/dagger-for-github@v5
        with:
          verb: call 
          module: github.com/mgreau/daggerverse/elasticsearch
          args: search --index="movies" --field="title" --query="Inception"
